export default {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  user: state => state.user.info,
  menu_type: state => state.user.menu_type,
  munuItems: state => state.user.munuItems,
  login_menu_role: state => state.user.login_menu_role,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  platform: state => state.permission.platform,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  configRules: state => state.waf.rules
}
